



name: 'dbt_code'
version: '1.0.0'

profile: 'dbt_code'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ register_upstream_external_models() }}"

models:
  dbt_code:
    dashboard_mart:
      +materialized: external
      +format: parquet
    
    