



name: 'dbt_code'
version: '1.0.0'

profile: 'dbt_code'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_code:
    for_dashboards:
      +materialized: external
      +plugin: s3
      +format: parquet
      +external_location: 's3://pfc-nfcu/dashboard_mart/{name}.parquet'  