dbt_code:  
  target: dev  
  outputs:
    dev: 
      type: duckdb 
      path: ':memory:'
      threads: 16
      extensions: 
        - httpfs
        - aws
      secrets: 
        - type: s3
          provider: credential_chain
          region: 'us-east-2'
         