dbt_code:  
  target: dev  
  outputs:
    dev: 
      type: duckdb 
      path: ':memory:'
      external_root: 's3://pfc-nfcu/dashboard_mart'
      threads: 4
      extensions: 
        - httpfs
        - aws
      secrets: 
        - type: s3
          provider: credential_chain
          region: 'us-east-2'
         