dbt_code:  
  target: dev  
  outputs:
    dev: 
      type: duckdb 
      path: ':memory:' 
      threads: 4
      extensions: 
        - httpfs
        - aws
      secrets: 
        - type: s3
          provider: credential_chain
         